### ISSUE TITLE
Bug in xferbench/xferbench/scripts/wikipedia.py update 

### ISSUE THREAD

**Issue by Charis-Graham** [brendon-boldt/xferbench#1]
On line 10, keyword "choice" should be "choices".

<img width="743" alt="Screenshot 2024-07-16 at 5 04 55 PM" src="https://github.com/user-attachments/assets/ac63e99a-a39c-4e3b-8ead-56b1e3edb87a">

**Comment by brendon-boldt** [comment]
Resolved by f3a31ff
